/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Align: typeof import('./src/components/align.vue')['default']
    Attribute: typeof import('./src/components/attribute.vue')['default']
    BackgroundBar: typeof import('./src/components/backgroundBar.vue')['default']
    BgBar: typeof import('./src/components/bgBar.vue')['default']
    BigPreview: typeof import('./src/components/bigPreview.vue')['default']
    CanvasMenu: typeof import('./src/components/canvasMenu.vue')['default']
    CenterAlign: typeof import('./src/components/centerAlign.vue')['default']
    Clone: typeof import('./src/components/clone.vue')['default']
    ColorSelector: typeof import('./src/components/colorSelector.vue')['default']
    CommonGrayBuntton: typeof import('./src/components/common/commonGrayBuntton.vue')['default']
    CommonIcon: typeof import('./src/components/commonIcon.vue')['default']
    Cropping: typeof import('./src/components/cropping.vue')['default']
    Del: typeof import('./src/components/del.vue')['default']
    Dialog: typeof import('./src/components/dialog.vue')['default']
    DragMode: typeof import('./src/components/dragMode.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    Filters: typeof import('./src/components/filters.vue')['default']
    Flip: typeof import('./src/components/flip.vue')['default']
    FontTmpl: typeof import('./src/components/fontTmpl.vue')['default']
    GreyBuntton: typeof import('./src/components/common/greyBuntton.vue')['default']
    GreyButton: typeof import('./src/components/common/greyButton.vue')['default']
    Group: typeof import('./src/components/group.vue')['default']
    History: typeof import('./src/components/history.vue')['default']
    ImportFile: typeof import('./src/components/importFile.vue')['default']
    ImportJSON: typeof import('./src/components/importJSON.vue')['default']
    ImportSvgEl: typeof import('./src/components/importSvgEl.vue')['default']
    ImportTmpl: typeof import('./src/components/importTmpl.vue')['default']
    InputNumber: typeof import('./src/components/inputNumber/inputNumber.vue')['default']
    Lang: typeof import('./src/components/lang.vue')['default']
    Layer: typeof import('./src/components/layer.vue')['default']
    Lock: typeof import('./src/components/lock.vue')['default']
    MapTile: typeof import('./src/components/mapTile.vue')['default']
    Pattern: typeof import('./src/components/pattern.vue')['default']
    PatternCard: typeof import('./src/components/patternCard.vue')['default']
    Paving: typeof import('./src/components/paving.vue')['default']
    PreviewCurrent: typeof import('./src/components/previewCurrent.vue')['default']
    ProductDetails: typeof import('./src/components/productDetails.vue')['default']
    ReplaceImg: typeof import('./src/components/replaceImg.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Save: typeof import('./src/components/save.vue')['default']
    SetSize: typeof import('./src/components/setSize.vue')['default']
    SmallPreview: typeof import('./src/components/smallPreview.vue')['default']
    SvgIcon: typeof import('./src/components/svgIcon/index.vue')['default']
    Test: typeof import('./src/components/test.vue')['default']
    Tools: typeof import('./src/components/tools.vue')['default']
    Zoom: typeof import('./src/components/zoom.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
